/*
 * Message types
 */


const messageTypes = {
    ACCESS_DENIED: "ACCESS_DENIED",
    INTERNAL_DB_ERROR: "INTERNAL_DB_ERROR",
    NAME_PASSWORD_INCORRECT: "NAME_PASSWORD_INCORRECT",
    USER_ALREADY_REGISTERED: "USER_ALREADY_REGISTERED",
    USER_LOGOUT: "USER_LOGOUT",

    GROUP_ALREADY_EXISTS: "GROUP_ALREADY_EXISTS",
    GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
    GROUP_UPDATE_INFO: "GROUP_UPDATE_INFO",
    GROUP_DELETE_INFO: "GROUP_DELETE_INFO",

    USER_GROUP_ADD_MEMBER_INFO: "USER_GROUP_ADD_MEMBER_INFO",
    USER_GROUP_REMOVE_MEMBER_INFO: "USER_GROUP_REMOVE_MEMBER_INFO",
    USER_GROUP_ACCESS_MEMBER_LIST_INFO: "USER_GROUP_ACCESS_MEMBER_LIST_INFO",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_UPDATED: "USER_ALREADY_UPDATED",

    MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",

    DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
    DEVICE_DEREGISTER_INFO: "DEVICE_DEREGISTER_INFO",
    DEVICE_UPDATE_INFO: "DEVICE_UPDATE_INFO",
    DEVICE_ALREADY_REGISTERED: "DEVICE_ALREADY_REGISTERED",

    DATABASE_NOT_FOUND: "DATABASE_NOT_FOUND",

};

module.exports = messageTypes;